# Generated by Django 4.2.4 on 2023-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('armName', models.CharField(max_length=50)),
                ('armDescription', models.TextField()),
                ('rusName', models.CharField(max_length=50)),
                ('rusDescription', models.TextField()),
            ],
        ),
    ]
