# Generated by Django 4.2.4 on 2023-08-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_tour_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('armName', models.CharField(max_length=50)),
                ('rusName', models.CharField(max_length=50)),
                ('places', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='preview',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.room')),
            ],
        ),
    ]
